name: "Code Scanning with Veracode and CodeQL"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '16 22 * * 1'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'javascript' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        queries: security-extended
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Veracode Pipeline Scan
      env:
        VERACODE_API_ID: ${{ secrets.VERACODE_API_ID }}
        VERACODE_API_KEY: ${{ secrets.VERACODE_API_KEY }}
        VERACODE_APP_NAME: Veracode GHAS Demo
        VERACODE_TEAM_NAME: Default Team
      run: |
        wget https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        unzip -o pipeline-scan-LATEST.zip
        cd pipeline-scan-LATEST
        chmod +x pipeline-scan.sh
        ./pipeline-scan.sh
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
